
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from './components/Footer'
import 'swiper/css';
import {Providers} from './providers'
import {CartProvider} from './context/CartContext'
import ClientLayout from './ClientLayout'
import PathLayout from './PathLayout'
import Script from "next/script";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "myAstrova",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
};

export default function RootLayout({ children }) {
  
  
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      
        <PathLayout> 
        <Providers className="pt-[120px]">
          <CartProvider>
        
        <ClientLayout>{children}</ClientLayout> 
           

          </CartProvider>
        </Providers>
        </PathLayout>

       
       

       
       <Script
  src="https://checkout.razorpay.com/v1/checkout.js"
  strategy="beforeInteractive"
/>

         
        
      </body>
    </html>
  );
}
